AWSTemplateFormatVersion: '2010-09-09'

Description: 'Simple cloudformation script'

Parameters:
  VpcCidrBlock:
    Description: 'State your VPC DR CIDR block'
    Type: String
    Default: '10.0.0.0/16'
  PublicSubnetACidrBlock:
    Description: 'State your Public Subnet A CIDR block'
    Type: String
    Default: '10.0.0.0/25'
  PrivateSubnetACidrBlock:
    Description: 'State your Private Subnet A CIDR block'
    Type: String
    Default: '10.0.10.0/25'

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Sub '${VpcCidrBlock}'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-VPC-DR'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-VPC-DR-IGW'
  IGWAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnetA:
    DependsOn: VPCCidrBlock
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: 'ap-southeast-2a'
      CidrBlock: !Sub '${PublicSubnetACidrBlock}'
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-VPC-DR-Public-Subnet-A'
  PrivateSubnetA:
    DependsOn: VPCCidrBlock
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: 'ap-southeast-2a'
      CidrBlock: !Sub '${PrivateSubnetACidrBlock}'
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-VPC-DR-Private-Subnet-A'